# was-manifests/k8s/base/was-db-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: was-db
  namespace: ksh-app
type: Opaque
stringData:
  DB_URL: mysql+pymysql://admin:soldesk901@project-db.c94ss824as09.ap-northeast-2.rds.amazonaws.com:3306/project?charset=utf8mb4

