apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-app
  labels:
    app: private-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      tolerations:
      - key: "role"
        operator: "Equal"
        value: "was"
        effect: "NoSchedule"
      nodeSelector:
        eks.amazonaws.com/nodegroup: Private-was
      containers:
        - name: private-container
          image: dgpark3675/mywas:v9
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: was-service
spec:
  type: ClusterIP
  selector:
    app: private-app
  ports:
    - port: 9000
      targetPort: 9000
  sessionAffinity: ClientIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: was-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: private-app
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300   # 최근 5분 평균으로 판단
      policies:
        - type: Percent
          value: 50                     # 한 번에 최대 50%까지 줄임
          periodSeconds: 60             # 60초마다 평가






