apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: was-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/soloud1025/was-manifests.git'   
    targetRevision: main
    path: .                                                     
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ksh-app                                          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
